name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -e .
          pip install pytest pytest-asyncio pyflakes
      - name: Lint (basic)
        run: |
          python -m pyflakes src || true
      - name: Run tests
        env:
          OPENROUTER_API_KEY: dummy
          AUGMENTOR_FAKE_EMBEDDINGS: "1"
        run: |
          pytest -q
